# 项目配置文件

# 数据配置
data:
  # 目标加密货币
  target_currencies:
    - BTC
    - ETH
    - BNB
    - XRP
    - ADA
  
  # 基础货币
  base_currency: USDT
  
  # 时间间隔（分钟）
  timeframes:
    - 1      # 1分钟
    - 5      # 5分钟
    - 15     # 15分钟
    - 60     # 1小时
    - 240    # 4小时
    - 1440   # 1天

  # 历史数据收集
  historical:
    lookback_days: 730  # 两年数据
    start_date: "2022-01-01"
    end_date: "2024-01-01"
  
  # 数据来源
  sources:
    - name: binance
      priority: 1
      api_key: ${BINANCE_API_KEY}
      api_secret: ${BINANCE_API_SECRET}
    
    - name: coinbase
      priority: 2
      api_key: ${COINBASE_API_KEY}
      api_secret: ${COINBASE_API_SECRET}

  # 数据存储
  storage:
    type: influxdb
    host: localhost
    port: 8086
    database: crypto_data
    username: ${INFLUXDB_USER}
    password: ${INFLUXDB_PASSWORD}

# 特征工程配置
features:
  # 技术指标窗口大小
  windows:
    short: [5, 10, 20]
    medium: [50, 100, 200]
    long: [500, 1000]
  
  # 特征组
  groups:
    - price_based      # 基于价格的特征
    - volume_based     # 基于交易量的特征
    - volatility       # 波动性特征
    - trend            # 趋势特征
    - momentum         # 动量特征
    - market_microstructure  # 市场微观结构特征

# 新增跨周期特征配置
feature_engineering:
  # 跨周期特征配置
  cross_timeframe_features:
    # 1小时周期特征 - 短期价格行为、波动性和交易量
    "1h": 
      - "vwap"              # 成交量加权平均价
      - "volume_delta"      # 交易量变化
      - "rsi_14"            # 相对强弱指数
      - "macd"              # 移动平均收敛/发散
      - "bbands_width"      # 布林带宽度
      - "atr_14"            # 平均真实范围
      - "price_change_20"   # 20周期价格变化
      - "volume_price_trend" # 交易量价格趋势
      - "obv"               # 能量潮
    
    # 4小时周期特征 - 中期趋势和势头
    "4h":
      - "sma_50"            # 50周期简单移动平均线
      - "ema_50"            # 50周期指数移动平均线
      - "price_rel_sma_50"  # 价格相对于SMA50的比率
      - "price_rel_ema_50"  # 价格相对于EMA50的比率
      - "adx_14"            # 平均方向指数
      - "aroon_oscillator"  # Aroon震荡指标
      - "cci_20"            # 商品通道指数
      - "tsi"               # 真实强度指数
    
    # 日线周期特征 - 长期趋势和市场结构
    "1d":
      - "sma_200"           # 200周期简单移动平均线
      - "ema_200"           # 200周期指数移动平均线
      - "price_rel_sma_200" # 价格相对于SMA200的比率
      - "ichimoku_a"        # 一目均衡图A线
      - "ichimoku_b"        # 一目均衡图B线
      - "mom_20"            # 20周期动量
      - "stoch_k"           # 随机指标K值
      - "stoch_d"           # 随机指标D值

# 模型配置
models:
  # 预测目标
  prediction_targets:
    - price_change_pct     # 价格变化百分比
    - direction            # 方向（上涨/下跌）
    - volatility           # 波动性预测
  
  # 预测时间窗口（分钟）
  prediction_horizons:
    short: [60, 240]       # 1小时, 4小时
    medium: [1440, 4320]   # 1天, 3天
    long: [10080, 20160]   # 7天, 14天
  
  # 特征集合
  feature_sets:
    selected_features_1h: ["vwap", "pvt", "sma_200", "price_rel_sma_100", "price_rel_ema_100", "ema_20_50_ratio", "ichimoku_b", "price_change_50", "roc_50", "price_impact_coef_200"]
    
    # 基于Ichimoku云图的特征集 - 侧重于趋势判断和价格关系
    ichimoku_based_set: [
      "ichimoku_b", 
      "ichimoku_base", 
      "ichimoku_a", 
      "ichimoku_conv", 
      "price_rel_sma_50", 
      "price_rel_ema_50", 
      "close", 
      "high", 
      "low",
      "adx_14"
    ]
    
    # 价格动量特征集 - 侧重于价格动量和趋势变化
    price_momentum_set: [
      "ema_10",
      "ema_20", 
      "sma_5", 
      "sma_20",
      "ema_20_50_ratio", 
      "sma_20_50_ratio",
      "macd", 
      "macd_signal", 
      "rsi_14", 
      "roc_10",
      "price_change_20",
      "momentum_10"
    ]
    
    # A型特征集 - 波动率和价格范围指标
    volatility_set: [
      "atr_14", 
      "true_range", 
      "bbands_width_20", 
      "keltner_width", 
      "high_low_diff", 
      "returns_volatility_20", 
      "garman_klass_vol", 
      "price_volatility",
      "close",
      "cci_14"
    ]
    
    # 交易量特征集 - 侧重于交易量和价格关系指标
    volume_based_set: [
      "volume", 
      "vwap", 
      "volume_change_pct", 
      "rel_volume_20", 
      "pvt", 
      "price_volume_corr_20", 
      "volume_oscillator", 
      "mfi_14",
      "obv",
      "price_impact_coef_200"
    ]
    
    # 综合特征集 - 结合重要特征和互补指标
    comprehensive_set: [
      "ichimoku_b",          # 趋势
      "ichimoku_base",       # 趋势
      "ema_10",              # 动量
      "rsi_14",              # 动量
      "atr_14",              # 波动率
      "bbands_width_20",     # 波动率
      "volume",              # 交易量
      "vwap",                # 交易量/价格
      "macd",                # 趋势/动量
      "price_rel_sma_50",    # 趋势强度
      "price_change_20",     # 价格行为
      "high_low_diff",       # 价格范围
      "close",               # 价格基准
      "adx_14",              # 趋势强度
      "mfi_14"               # 资金流向
    ]
  
  # 模型类型
  model_types:
    - lstm
    - gru
    - transformer
    - xgboost
    - lightgbm
    - ensemble
  
  # 训练参数
  training:
    test_size: 0.2
    val_size: 0.1
    shuffle: false
    batch_size: 64
    epochs: 100
    early_stopping: 10
    learning_rate: 0.001

# 评估配置
evaluation:
  metrics:
    - direction_accuracy
    - rmse
    - mae
    - sharpe_ratio
    - max_drawdown
  
  # 回测参数
  backtest:
    initial_capital: 10000
    trading_fee: 0.001
    slippage: 0.0005

# 系统配置
system:
  # 日志配置
  logging:
    level: INFO
    file: logs/crypto_prediction.log
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # API服务配置
  api:
    host: 0.0.0.0
    port: 8000
    debug: false 